[package]
name = "mokuba"
version = "0.0.1"
edition = "2021"
authors = ["Samuel G <samgj_18@hotmail.com>"]

[[bin]]
name = "mo"
path = "src/bin.rs"

[dependencies]
mcore = { path = "lib/mcore" }
mmacro = { path = "lib/mmacro" }

[workspace]
members = ["lib/mcore", "lib/mmacro"]
