name: Release

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    push:
      tags:
        - "v*.*.*"
    types: 
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1